apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  namespace: prod
  labels:
    app: podlb
spec:
  containers:
    - name: my-pod-co
      image: nginx
      ports:
        - containerPort: 80

      startupProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 14
        periodSeconds: 10
        failureThreshold: 5
        successThreshold: 1

      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 14
        periodSeconds: 10
        failureThreshold: 5
        successThreshold: 1

      readinessProbe:
        tcpSocket:
          port: 80
        initialDelaySeconds: 14
        periodSeconds: 10
        failureThreshold: 5
        successThreshold: 1